/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_android_server_WiredAccessoryManager */

#ifndef _COM_ANDROID_SERVER_WiredAccessoryManager_H
#define _COM_ANDROID_SERVER_WiredAccessoryManager_H

#include "JNIHelp.h"
#include "jni.h"


namespace android {

extern   jchar  com_android_server_WiredAccessoryManager_returnSpkDet (JNIEnv * env, jobject cls);

extern   jchar  com_android_server_WiredAccessoryManager_returnAIOSetting (JNIEnv * env, jobject cls);

extern   jchar com_android_server_WiredAccessoryManager_returnIntSpkSetting (JNIEnv * env, jobject cls);

}
#endif // _COM_ANDROID_SERVER_WiredAccessoryManager_H

